# Generated by Django 5.2.14 on 2026-09-14 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_customer_arabic_name_customer_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='crm.customer'),
        ),
        migrations.AddField(
            model_name='lead',
            name='next_follow_up',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
    ]
